Рендер выбора даты в сафари
KatySolo/realtimepollreact pull request #30
Opened 2020-04-17 14:36 UTC by JulieBlack666

Нашла готовый кроссбраузерный вариант на реакте. Если надо, можно попробовать кастомизировать поле инпута, добавив иконку календарика или стрелочку вниз

2020-04-17 14:37 UTC, JulieBlack666 commented
На IE кстати ещё не проверила, сейчас возьмусь

2020-04-17 15:12 UTC, KatySolo requested changes

2020-04-17 15:12 UTC, KatySolo commented on src/components/SessionWindows/SessionForm/SessionForm.jsx
> +		console.log(start);
Хехе

2020-04-17 15:12 UTC, KatySolo commented on src/components/SessionWindows/SessionsList/SessionsList.jsx
> +										<td className='start_cell'>{result.start}</td>
Все время хранится в UTC, поэтому тут надо вернуть как было
Или что то поменялось?

2020-04-17 15:14 UTC, JulieBlack666 commented on src/components/SessionWindows/SessionForm/SessionForm.jsx
> +		console.log(start);
Упс😅

2020-04-17 15:15 UTC, KatySolo commented
@JulieBlack666 
А можешь еще скринов сюда накидать?

2020-04-17 15:15 UTC, JulieBlack666 commented on src/components/SessionWindows/SessionsList/SessionsList.jsx
> +										<td className='start_cell'>{result.start}</td>
Ну короче в нынешнем варианте выглядит вот так
<img width="1680" alt="Снимок экрана 2020-04-17 в 20 15 20" src="https://user-images.githubusercontent.com/32227117/79584722-3816ae80-80e8-11ea-9d28-7937eb26dc34.png">

2020-04-17 15:17 UTC, KatySolo commented
+ я с датами работаю в #25 
Возможно будут конфликты

2020-04-17 15:18 UTC, JulieBlack666 commented
> @JulieBlack666
> А можешь еще скринов сюда накидать?

1) сафари
<img width="502" alt="Снимок экрана 2020-04-17 в 20 16 57" src="https://user-images.githubusercontent.com/32227117/79584941-84fa8500-80e8-11ea-80e6-e85780ef17a9.png">

2) хром
<img width="422" alt="Снимок экрана 2020-04-17 в 20 17 13" src="https://user-images.githubusercontent.com/32227117/79584959-8d52c000-80e8-11ea-8d98-3c2d3abb2ecd.png">

2020-04-17 15:18 UTC, JulieBlack666 commented
Кажется, со стилями инпута надо повозиться ещё, они немного разные

2020-04-17 15:20 UTC, JulieBlack666 commented
> * я с датами работаю в #25
>   Возможно будут конфликты

Ну смёржимся как-нибудь

2020-04-17 15:20 UTC, JulieBlack666 commented on src/components/SessionWindows/SessionsList/SessionsList.jsx
> +										<td className='start_cell'>{result.start}</td>
Так норм или менять?

2020-04-17 15:21 UTC, JulieBlack666 commented on src/components/SessionWindows/SessionsList/SessionsList.jsx
> +										<td className='start_cell'>{result.start}</td>
Могу ещё чекнуть, не меняется ли часовой пояс от выбранного или типа того

2020-04-17 15:22 UTC, JulieBlack666 commented on src/components/SessionWindows/SessionsList/SessionsList.jsx
> +										<td className='start_cell'>{result.start}</td>
Просто через newDate эти строчки тоже не парсятся, invalid date везде

2020-04-17 15:25 UTC, KatySolo commented on src/components/SessionWindows/SessionsList/SessionsList.jsx
> +										<td className='start_cell'>{result.start}</td>
А время получается отобраается не в нашем поясе?

2020-04-17 15:27 UTC, KatySolo commented on src/components/SessionWindows/SessionsList/SessionsList.jsx
> +										<td className='start_cell'>{result.start}</td>
> Так норм или менять?

Просто я не понимаю куда смотреть))

2020-04-17 15:35 UTC, JulieBlack666 commented on src/components/SessionWindows/SessionsList/SessionsList.jsx
> +										<td className='start_cell'>{result.start}</td>
Так, а в инпуте получается надо в UTC время передавать в результате, а потом тут его обратно переводить, получается?

2020-04-17 15:39 UTC, JulieBlack666 commented on src/components/SessionWindows/SessionsList/SessionsList.jsx
> +										<td className='start_cell'>{result.start}</td>
> А время получается отображается не в нашем поясе?

Оно просто отображается так же, как было задано в инпуте, про пояса я как-то не задумывалась

2020-04-17 15:41 UTC, KatySolo commented on src/components/SessionWindows/SessionsList/SessionsList.jsx
> +										<td className='start_cell'>{result.start}</td>
Вводить в инпут нужно в нашем поясе, на бэк подавать в UTC, c бека приходит UTC и надо его показать в нашем поясе.

2020-04-17 15:41 UTC, JulieBlack666 commented on src/components/SessionWindows/SessionsList/SessionsList.jsx
> +										<td className='start_cell'>{result.start}</td>
Если надо межпоясной вариант, то, возможно, стоит из инпута посылать время переведённое в UTC, а потом переводить обратно

2020-04-17 15:41 UTC, JulieBlack666 commented on src/components/SessionWindows/SessionsList/SessionsList.jsx
> +										<td className='start_cell'>{result.start}</td>
> Вводить в инпут нужно в нашем поясе, на бэк подавать в UTC, c бека приходит UTC и надо его показать в нашем поясе.

Да блин, у меня комменты не обновляются хех

Лан, ща подумою, как это сделать

2020-04-17 15:44 UTC, KatySolo commented
> Ну смёржимся как-нибудь

Я посмотрела, можно не париться на этот счет

2020-04-17 16:08 UTC, JulieBlack666 commented on src/components/SessionWindows/SessionsList/SessionsList.jsx
> +										<td className='start_cell'>{result.start}</td>
Так, стоп, у тебя на сервереуже переводится в localeString
<img width="535" alt="Снимок экрана 2020-04-17 в 21 06 38" src="https://user-images.githubusercontent.com/32227117/79589878-8a0f0280-80ef-11ea-9c59-1132700e952b.png">

2020-04-17 16:08 UTC, JulieBlack666 commented on src/components/SessionWindows/SessionsList/SessionsList.jsx
> +										<td className='start_cell'>{result.start}</td>
Хотя, не совсем понятно, какая локаль у сервера хм

2020-04-17 16:09 UTC, JulieBlack666 commented on src/components/SessionWindows/SessionsList/SessionsList.jsx
> +										<td className='start_cell'>{result.start}</td>
Но я уже явно перевожу в UTC перед отправкой, и при получении данных с сервера всё равно время в нужном поясе

2020-04-17 16:09 UTC, JulieBlack666 commented on src/components/SessionWindows/SessionsList/SessionsList.jsx
> +										<td className='start_cell'>{result.start}</td>
Надо попробовать потестить у ноута пояс сменить или типа того хм

2020-04-17 16:15 UTC, KatySolo commented on src/components/SessionWindows/SessionsList/SessionsList.jsx
> +										<td className='start_cell'>{result.start}</td>
https://github.com/KatySolo/realtimepoll_server/pull/21

тут выпил будет

2020-04-17 16:15 UTC, KatySolo commented on src/components/SessionWindows/SessionsList/SessionsList.jsx
> +										<td className='start_cell'>{result.start}</td>
давай придерживаться такой схемы
https://github.com/KatySolo/realtimepollreact/pull/30#discussion_r410306352

2020-04-17 16:16 UTC, JulieBlack666 commented on src/components/SessionWindows/SessionsList/SessionsList.jsx
> +										<td className='start_cell'>{result.start}</td>
Короче как вариант с сервера toLocaleString убрать и делать только при отрисовке, чтобы было явно понятно, что берется локаль с клиента, и ещё так дата не ломается

2020-04-17 16:16 UTC, JulieBlack666 commented on src/components/SessionWindows/SessionsList/SessionsList.jsx
> +										<td className='start_cell'>{result.start}</td>
Да блин, чё у меня так поздно комменты обновляются

2020-04-17 16:17 UTC, JulieBlack666 commented on src/components/SessionWindows/SessionsList/SessionsList.jsx
> +										<td className='start_cell'>{result.start}</td>
> [KatySolo/realtimepoll_server#21](https://github.com/KatySolo/realtimepoll_server/pull/21)
> 
> тут выпил будет

выпил localeString на сервере?

2020-04-17 16:17 UTC, KatySolo commented on src/components/SessionWindows/SessionsList/SessionsList.jsx
> +										<td className='start_cell'>{result.start}</td>
тогда давай я залью в мастер ветку сервера и ты накатишь себе изменения?

2020-04-17 16:18 UTC, KatySolo commented on src/components/SessionWindows/SessionsList/SessionsList.jsx
> +										<td className='start_cell'>{result.start}</td>
> Короче как вариант с сервера toLocaleString убрать и делать только при отрисовке, чтобы было явно понятно, что берется локаль с клиента, и ещё так дата не ломается

в моем PR есть

2020-04-17 16:18 UTC, JulieBlack666 commented on src/components/SessionWindows/SessionsList/SessionsList.jsx
> +										<td className='start_cell'>{result.start}</td>
Да окей, верю, тогда сейчас сделаю так, как ты сказала всё, и залью

2020-04-19 07:24 UTC, KatySolo commented
@JulieBlack666 

Я влила ветку на сервер с датами

2020-04-19 12:57 UTC, JulieBlack666 commented
@KatySolo 

Глянула с изменениями на сервере, вроде ок работает. Перевод даты чуть раньше уже залила, можешь глянуть

2020-04-20 12:41 UTC, KatySolo approved these changes

2020-04-21 12:50 UTC, merged