Возможность удаления сессий и пользователей на клиенте
KatySolo/realtimepollreact pull request #34
Opened 2020-04-24 15:48 UTC by JulieBlack666

Closes #31 

VS code стирает перенос строки в css файлах, у меня пока не получается с этим разобраться(((

2020-04-27 05:37 UTC, KatySolo requested changes

2020-04-27 05:37 UTC, KatySolo commented on src/components/CrossIcon/CrossIcon.jsx
> +				<div data-tip={this.props.question} onClick={this.onClick} className="cross-icon">
Тут можно сразу из props вызывать onClick, без дополнительного метода в классе

2020-04-28 07:48 UTC, KatySolo commented
@JulieBlack666 

Смерджишь после #37 или мне лучше?

2020-04-28 08:08 UTC, JulieBlack666 commented
> @JulieBlack666
> 
> Смерджишь после #37 или мне лучше?

Сейчас посмотрю, думаю, смёржу, но если что позову

2020-04-28 08:15 UTC, KatySolo approved these changes

2020-04-28 08:41 UTC, JulieBlack666 commented
Единственное, непонятно, куда засунуть мою компоненту CrossIcon или пока просто в components оставить?

2020-04-28 08:47 UTC, JulieBlack666 commented
@KatySolo  У меня какеая-то странная ошибка, когда пытаюсь смерженные изменения запушить. Может, попробовать снова запросить у тебя approve?
<img width="670" alt="Снимок экрана 2020-04-28 в 13 47 35" src="https://user-images.githubusercontent.com/32227117/80467103-d3184f80-8956-11ea-8765-74f14965031c.png">

2020-04-28 08:50 UTC, KatySolo commented
> Единственное, непонятно, куда засунуть мою компоненту CrossIcon или пока просто в components оставить?

Да, в components

2020-04-28 08:51 UTC, KatySolo commented
> @KatySolo У меня какеая-то странная ошибка, когда пытаюсь смерженные изменения запушить. Может, попробовать снова запросить у тебя approve?

Approve есть
А как ты мерджишь?

2020-04-28 08:53 UTC, JulieBlack666 commented
> > @KatySolo У меня какеая-то странная ошибка, когда пытаюсь смерженные изменения запушить. Может, попробовать снова запросить у тебя approve?
> 
> Approve есть
> А как ты мерджишь?

Ну я у себя локально мастер обновила до последней версии, потом перешла сюда в ветку deleting-enabled, выполнила команду git merge master, в вскоде всё зарезолвила и поправила, и вот пытаюсь сделать пуш сюда же, но выдаёт вот эту ошибку

2020-04-28 08:55 UTC, JulieBlack666 commented
Вообще, если у меня с этой фигней разобраться не получиться, то там из мерджа только файл package.json и ещё компоненты UserListItem и SessionListItem в нынешнюю папку к листам перенести

2020-04-28 08:55 UTC, KatySolo commented
> > > @KatySolo У меня какеая-то странная ошибка, когда пытаюсь смерженные изменения запушить. Может, попробовать снова запросить у тебя approve?
> > 
> > 
> > Approve есть
> > А как ты мерджишь?
> 
> Ну я у себя локально мастер обновила до последней версии, потом перешла сюда в ветку deleting-enabled, выполнила команду git merge master, в вскоде всё зарезолвила и поправила, и вот пытаюсь сделать пуш сюда же, но выдаёт вот эту ошибку

Сейчас попробую убрать ограничения и должно получиться

2020-04-28 09:14 UTC, JulieBlack666 commented
Заработало

2020-04-28 09:23 UTC, merged