Изменение архитектуры
KatySolo/realtimepollreact pull request #37
Opened 2020-04-27 08:50 UTC by KatySolo

2020-04-27 16:18 UTC, KatySolo commented
@JulieBlack666 @JudithRomero 

Посмотрите новый вариант архитектуры. Ревью очень приветсвуется.

2020-04-27 16:34 UTC, JulieBlack666 commented on src/components/functional/Calendar/Calendar.jsx
> + * Каелндарь для выбора даты
Мелочь, но тут очепятка

2020-04-27 16:37 UTC, JulieBlack666 commented on src/components/functional/Input/Input.jsx
> +		} else return (
Дело вкуса, но можно обойтись и без else

2020-04-27 16:46 UTC, JulieBlack666 commented on src/components/functional/Rating/Raiting.jsx
> +	isValidValue (value) {
Немного кажется не подходит тут название функции, is как-то предполагает, что она должна вернуть булево значение. Может, попробовать что-нибудь вроде checkIfValidValue или там checkIfInputValid ну или что-то подобное?

2020-04-27 16:48 UTC, JulieBlack666 commented on src/components/functional/Rating/Raiting.jsx
> +		if (value < this.props.min ||value > this.props.max) {
Вообще насколько вижу, тут можно без ифа обойтись. Коллбэк в обоих случаях одинаковый, а в значение isValid можно отправить отрицание к условию из ифа

2020-04-27 16:51 UTC, JulieBlack666 commented on src/components/functional/Rating/RaitingN.js
> +		if (props.n !== props.labels.length && props.n !== props.ids.length) {
А тут точно должно быть и, а не или?

2020-04-27 16:52 UTC, JulieBlack666 commented on src/components/functional/Rating/RaitingN.js
> +		console.log(surveyScore);
console.log подчистить забыла

2020-04-27 16:57 UTC, JulieBlack666 commented on src/components/functional/Rating/RaitingN.js
> +import Rating from './Raiting';
Кстати, имена файлов Raiting и RaitingN возможно, стоит подправить и убрать лишнюю i

2020-04-27 17:08 UTC, JulieBlack666 requested changes
Большинство получилось придирок по стилю, но их можно оспорить и объяснить, почему я не права

2020-04-28 07:07 UTC, KatySolo commented on src/components/functional/Rating/RaitingN.js
> +		if (props.n !== props.labels.length && props.n !== props.ids.length) {
Если поставить или, то можно допустить ситуацию, когда n !== labels.length, но  n === ids.length (id есть, а названия поля нет). Аналогично и обратное. Мне кажется, это неверное поведение.

2020-04-28 07:39 UTC, JulieBlack666 commented on src/components/functional/Rating/RaitingN.js
> +		if (props.n !== props.labels.length && props.n !== props.ids.length) {
Хм, ну ведь по сути мы тут хотим кидать ошибку как раз, если хотя бы что-то одно не равно, а с и мы кинем только если оба не равны

2020-04-28 07:40 UTC, JulieBlack666 commented on src/components/functional/Rating/RaitingN.js
> +		if (props.n !== props.labels.length && props.n !== props.ids.length) {
(тут в ифе ошибка кидается)

2020-04-28 07:44 UTC, KatySolo commented
@JulieBlack666 

Теперь можно смотреть

2020-04-28 07:58 UTC, JulieBlack666 commented on src/components/functional/Rating/RaitingN.js
> +		if (props.n !== props.labels.length && props.n !== props.ids.length) {
@KatySolo всё-таки тут не уверена по поводу и, посмотри

2020-04-28 08:03 UTC, KatySolo commented on src/components/functional/Rating/RaitingN.js
> +		if (props.n !== props.labels.length && props.n !== props.ids.length) {
@JulieBlack666 
Да, ты права, тут надо 'или' ставить. Сейчас поправлю 🦒

2020-04-28 08:05 UTC, JulieBlack666 approved these changes

2020-04-28 08:11 UTC, merged